### ISSUE TITLE
type: scratch doesn't support run

### ISSUE THREAD

**Issue by hallyn** [project-stacker/stacker#26]
```
$ cat stacker.yaml
t1:
  from:
    type: scratch
  import:
    - /etc/hosts
  run:
    - cp /scratch/hosts /
$ sudo -E stacker build
building image t1...
importing files...
copying /etc/hosts
running commands...
running commands for t1
failed to start container .working
error: run commands failed: execute failed
Last few LXC errors:
lxc .working 20190214150043.627 ERROR    execute - execute.c:execute_start:93 - No such file or directory - Failed to exec lxc-init
lxc .working 20190214150043.628 ERROR    sync - sync.c:__sync_wait:62 - An error occurred in another process (expected sequence number 7)
lxc .working 20190214150043.628 ERROR    start - start.c:__lxc_start:1972 - Failed to spawn container ".working"
```

**Comment by tych0** [comment]
On Thu, Feb 14, 2019 at 07:27:52AM -0800, Serge Hallyn wrote:
> ```
> $ cat stacker.yaml
> t1:
>   from:
>     type: scratch
>   import:
>     - /etc/hosts
>   run:
>     - cp /scratch/hosts /
> $ sudo -E stacker build
> building image t1...
> importing files...
> copying /etc/hosts
> running commands...
> running commands for t1
> failed to start container .working
> error: run commands failed: execute failed
> Last few LXC errors:
> lxc .working 20190214150043.627 ERROR    execute - execute.c:execute_start:93 - No such file or directory - Failed to exec lxc-init
> lxc .working 20190214150043.628 ERROR    sync - sync.c:__sync_wait:62 - An error occurred in another process (expected sequence number 7)
> lxc .working 20190214150043.628 ERROR    start - start.c:__lxc_start:1972 - Failed to spawn container ".working"
> ```

Heh, yeah :(. I wonder if we should bind mount in some stuff? The
problem is that it creates an empty rootfs, and then there's nothing
in there to execute.

**Comment by hallyn** [comment]
> Heh, yeah :(. I wonder if we should bind mount in some stuff? The
> problem is that it creates an empty rootfs, and then there's nothing
> in there to execute.

Right, so the run portion should probably just detect what's missing
and fake it...  I actually thought lxc would take care of that for us.

Oh, actually maybe this isn't stacker's fault:

$ ldd /usr/sbin/init.lxc.static
        linux-vdso.so.1 =>  (0x00007ffe445b9000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7f21401000)
        libcap.so.2 => /lib/x86_64-linux-gnu/libcap.so.2 (0x00007f7f211fb000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7f20e31000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f7f2182e000)


I thought we fixed this in lxc's packaging!

**Comment by tych0** [comment]
On Thu, Feb 14, 2019 at 08:02:17AM -0800, Serge Hallyn wrote:
> > Heh, yeah :(. I wonder if we should bind mount in some stuff? The
> > problem is that it creates an empty rootfs, and then there's nothing
> > in there to execute.
> 
> Right, so the run portion should probably just detect what's missing
> and fake it...  I actually thought lxc would take care of that for us.

How would we detect what's missing? You mean bind mount in any binary
that the user tries to execute but doesn't exist in the rootfs? What
about things that are exec'd from inside something else? Maybe
seccomp-user-trap with a just in time mount? :)

> Oh, actually maybe this isn't stacker's fault:
> 
> $ ldd /usr/sbin/init.lxc.static
>         linux-vdso.so.1 =>  (0x00007ffe445b9000)
>         libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7f21401000)
>         libcap.so.2 => /lib/x86_64-linux-gnu/libcap.so.2 (0x00007f7f211fb000)
>         libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7f20e31000)
>         /lib64/ld-linux-x86-64.so.2 (0x00007f7f2182e000)
> 
> 
> I thought we fixed this in lxc's packaging!

It still won't work even if we fix this -- the rootfs is empty, so
when you try to run `touch` or `cp` or whatever, it will fail.

**Comment by hallyn** [comment]
Oh right.  wasn't thinking of 'cp' :)

Sounds like we might want a 'busybox' automatically imported.
And, for optimum coolness factor, perhaps type:scratch should
remove all the busybox links when generating the layer.  Don't
ask me how, you're the magician.

**Comment by tych0** [comment]
Another option is to stick a statically linked busybox install in `/stacker/.bin` and put that in `$PATH`, since stacker sets `$PATH` anyway.

**Comment by rchincha** [comment]
Doesn't look like a stacker-specific limitation.
"scratch" is useful only in packaging self-contained static binaries?

```
$ cat Dockerfile
FROM scratch
RUN bash
```

```
$ docker build -f Dockerfile .
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM scratch
 --->
Step 2/2 : RUN bash
 ---> Running in b436e69d5e08
OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory": unknown
```

**Comment by tych0** [comment]
Yes, agreed that it's not stacker specific. We could do something nice here though; in fact just before the break someone had a really nice idea for how to solve this and I don't think we wrote it down, and now I've forgotten it :(

**Comment by mikemccracken** [comment]
so, @hallyn @tych0 did we decide not to do this?

**Comment by hallyn** [comment]
Indeed, that's my understanding.  Closing.

**Comment by rchincha** [comment]
We now support "from: scratch"
